spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/seckill_system?characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
logging:
  level:
    com:
      example:
        mapper : debug