server:
  port: 8000
spring:
  application:
    name:  seckill-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mikeygithub/seckill-config.git #GitHub上面的git仓库名字
          force-pull: true #强行拉取
          ignore-local-ssh-settings: true # If true, use property based SSH config instead of file based.
