#server
server:
  port: 9527
#spring
spring:
  application:
    name: seckill-zuul-gateway
#eureka
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
  instance:
    instance-id: seckill-zuul-gateway
    prefer-ip-address: true
##info
#info:
#  app.name: seckill-zuul-gateway
#  company.name: www.seckill.com
#  build.artifactId: $project.artifactId$
#  build.version: $project.version$
#zuul
zuul:
  ignored-services: "*"
  routes:
    seckill-service-sys-porvider:
      path: /sys/**
    seckill-service-kill-porvider:
      path: /kill/**
    seckill-service-admin:
      path: /admin/**
management:
  endpoints:
    web:
      exposure:
        include: 'routes'
#jwt配置
secktll:
  jwt:
    # 加密秘钥
    secret: f4e2e52034348f86b67cde581c0f9eb5
    # token有效时长，7天，单位秒
    expire: 604800
    header: authorization