spring:
  profiles:
    active:
      - dev
---
server:
  port: 8301
spring:
  profiles: dev
  application:
    name: seckill-service-admin
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
---
server:
  port: 8302
spring:
  profiles: test
  application:
    name: seckill-service-admin
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/