spring:
  profiles:
    active:
      - dev
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/seckill_system?characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
logging:
  level:
    com:
      example:
        mapper : debug
---
server:
  port: 8501
spring:
  profiles: dev
  application:
    name: seckill-service-kill-porvider
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
---
server:
  port: 8502
spring:
  profiles: test
  application:
    name: seckill-service-kill-porvider
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/