spring:
  application:
    name: seckill-eureka
  freemarker:
    prefer-file-system-access: false
server:
  port: 8761
eureka:
  instance:
    hostname: localhost #服务端的实例名称
  client:
    register-with-eureka: false #false表示不向注册中心注册自己
    fetch-registry: false #false表示自己就是注册中心,我的职责就是维护实例,并不是需要去检索服务
    service-url:
      defaultZone: http://localhost:8761/eureka/ #设置与Eureka Server交互的地址查询服务和注册服务
  server:
    enable-self-preservation: false
